apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: btmesh-operator
spec:
  output:
    to:
      kind: ImageStreamTag
      name: btmesh-operator:latest
  source:
    git:
      ref: main
      uri: https://github.com/drogue-iot/btmesh-operator.git
    type: Git
  strategy:
    type: Docker
  triggers:
  - type: ConfigChange
